### ISSUE TITLE
Framework / Colors

### ISSUE THREAD

**Issue by notjb** [studiometa/scss-toolkit#15]
When using the color function, i'm getting the following error : 

SCSS
```scss

$colors: (
  'grey': #f4f7fb,
  'white': #fff,
  'green': #86bc25,
);

color(white);
```

Error
```js
Error: node_modules/@studiometa/scss-toolkit/src/framework/_colors.scss
  Error: No color found in the `$colors` map for `white`.
          on line 20 of node_modules/@studiometa/scss-toolkit/src/framework/_colors.scss, in function `color`
          from line 4 of web/wp-content/themes/es-photovoltaique/assets/src/styles/components/_cta-button.scss
          from line 17 of web/wp-content/themes/es-photovoltaique/assets/src/styles/app.scss
  >>     @error 'No color found in the `$colors` map for `#{$color}`.';
     ----^
````
**Main issue :** no fallback is made to the default `$colors` map.
**Bugfix :** The problem can be solved by only using strings as parameter of the function.
**Potential Feature request :** make both strings and keys usable or fallback to default `$colors` map

**Comment by titouanmathis** [comment]
The problem was coming from the key `white` also being a CSS color keyword. The type of `$color` in the function was then `color` instead of `string`, which made it throw an error.

Casting the parameter as a string seems to resolve the issue. Will be fixed in the 1.2.0 release 😉
