### ISSUE TITLE
Add extendable maps

### ISSUE THREAD

**Issue by lusimeon** [studiometa/scss-toolkit#19]
Inspired by bootstrap maps. Add the possibility to extend default maps to prevent rewriting the all map values.

See the example below:

__colors.scss_
```scss
$colors: () !default;
$colors: map-merge(
  (
    "white": #fff,
    "black": #000
  ),
  $colors
);
```
__config.scss_
```scss
$colors: (
    "custom-color": #900
);
```

**Comment by w-jerome** [comment]
I think the idea is interesting.

But I'm not sure it's relevant, if on my PSD I have the black color of the site which is #111111. So I can't use the "black" key, I should use a "black-custom" key. And I don't think it's productive.

And moreover, if we apply this rule to spaces, or breakpoints. The generated CSS will create a lot of unnecessary variations on the site.

**Comment by lusimeon** [comment]
@w-jerome You can overwrite existing default keys with this method too. If you add a key in your custom colors array who already exists in default colors array, it will overwrite this default key. So you don't need to create a "black-custom" color.

The file size will be equal to the size of the actualy generated file. The resulting CSS will be the same as actually ;)

**Comment by titouanmathis** [comment]
@lusimeon I agree with you, and it seems like a good enhancement.

My only concern would be on how to avoid generating helper classes for the default values if my project does not have any white or black. I think we should be able to choose if we want to merge or if we want to override the default configuration with our own.

Maybe with a custom configuration? See the following exampe: 

```sass
$colors-merge-defaults: true !default;

$colors: () !default;

@if $colors-merge-defaults {
  $colors: map-merge(
    (
      "white": #fff,
      "black": #000
    ),
    $colors
  );
}
```

**Comment by titouanmathis** [comment]
@lusimeon I suggest to close this issue as it is not blocking and, I think, a little bit complicated to implement.  What do you think?

**Comment by lusimeon** [comment]
@titouanmathis You're right, there is no ideal solution for all cases… 

[The one above](https://github.com/studiometa/scss-toolkit/issues/19#issuecomment-478732270) must not be implemented because it will multiply way to use maps in the project and so possibly  increase errors due to differents used ways between projects.

Another solution can be to add extendable maps only for the ones who always have same basis in our projects (eg: breakpoints, spaces, weight) and just override the ones who change often in depends of project (colors, layers, font-faces). But it will multiply the way maps are used by the toolkit and so, complicate the usage of these ones and the toolkit documentation.

Maybe we can just add a `enhancement` label to keep in mind instead of place it to trash.

**Comment by titouanmathis** [comment]
I am closing it for now, we can still create a new one later with a reference to this one 😉
