### ISSUE TITLE
Add a flex value in the displays default values

### ISSUE THREAD

**Issue by ThomasCtnt** [studiometa/scss-toolkit#27]
Wouldn't it be useful to add the flex value in the $displays array ? We actually have to define it in the config

**Comment by titouanmathis** [comment]
The `display: flex` property has been migrated to the `_flex.scss` file with all the flex helpers definitions. It is not yet documented, but you can have a look at the [original file](https://github.com/studiometa/scss-toolkit/blob/master/src/framework/_flex.scss) 😉 

The following classes are available to use:
- `.flex`: set the `display` property to `flex`
- `.flex-inline`: set the `display` property to `inline-flex`
- `.flex--<breakpoint>`: same as `.flex`, but for the given `<breakpoint>`
- `.flex-inline--<breakpoint>`: same as `.flex-inline`, but for the given `<breakpoint>`
