### ISSUE TITLE
[v3 beta] @mixin font-size bug calcul

### ISSUE THREAD

**Issue by w-jerome** [studiometa/scss-toolkit#48]
_config.scss
```
$type-sizes : (
  body : (
    default : (
      font-size: 16px,
      line-height: 28px,
    ),
    s : (
      font-size: 18px,
      line-height: 32px,
    ),
  ),
) ;
```

When I do a `@include font-size('body')` it returns `font-size: /16pxem;` so I can't display my font size correctly.

**Comment by titouanmathis** [comment]
You have to use `size` keys instead of `font-size` : 
```scss
$type-sizes : (
  body : (
    default : (
      size: 16px,
      line-height: 28px,
    ),
    s : (
      size: 18px,
      line-height: 32px,
    ),
  ),
) ;
```
See the `map-get` function in the source file : https://github.com/studiometa/scss-toolkit/blob/release/3.0.0/src/framework/_typography.scss#L131.
